#!/bin/env bash

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configure Nginx to listen on port 80 and serve Hello World
sudo echo "server {
    listen 80;
    server_name _;

    location / {
        root /var/www/html;
        index index.html;
        add_header Content-Type text/html;
        return 200 'Hello World!\n';
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx
sudo kill -s HUP $(cat /var/run/nginx.pid)
