#!/usr/bin/env bash

# Install Nginx if not already installed
sudo apt-get update
sudo apt-get install -y nginx

# Configure Nginx for redirection
sudo echo "server {
    listen 80;
    server_name _;

    location / {
        root /var/www/html;
        index index.html;
        add_header Content-Type text/html;
        return 200 'Hello World!\n';
    }

    location /redirect_me {
        return 301 http://www.google.com;
    }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Restart Nginx
sudo kill -s HUP $(cat /var/run/nginx.pid)
