#!/usr/bin/env bash
# Script that displays numbers from 0-10 with style.

for ((num = 1; num <= 100; num++)); do
	if ((num%3 == 0 && num%5 == 0)); then
		printf "FizzBuzz\n"
	elif ((num%3 == 0)); then
		printf "Fizz\n"
	elif ((num%5 == 0)); then
		printf "Buzz\n"
	else
		printf "%d\n" "$num"
	fi
done
