#!/usr/bin/env bash
# Script that displays the content of the file /etc/passwd

# Check if /etc/passwd exists
if [[ -f /etc/passwd ]]; then
    # Read the file line by line
    while IFS=: read -r username _ uid _ home _; do
        echo "$username:$uid:$home"
    done < /etc/passwd
else
    echo "/etc/passwd does not exist."
fi
