#!/usr/bin/env bash
# Script that displays a story with the content of the file /etc/passwd

# Check if /etc/passwd exists
if [[ -f /etc/passwd ]]; then
    # Read the file line by line
    while IFS=: read -r username _ uid _ home _; do
        IFS=',' read -ra user_info <<< "$info"
        user_id_info="${user_info[4]}"
        password="${user_info[5]}"
        echo "The user $username is part of the $gid gang, lives in $home, and rides $shell. USER ID's place is protected by the passcode $password, more info about the user here: $user_id_info"
    done < /etc/passwd
else
    echo "/etc/passwd does not exist."
fi
