#!/usr/bin/env bash
# Script that prints "Best School" 10 times, using "while" and include "Hi" at the 9th call.

words='Best School'
i=0

while ((i < 10)); do
	if ((i == 9)); then
		printf "Hi\n"
	fi
	printf "%s\n" "$words"
	((i++))
done
