#!/usr/bin/env bash
# Script that prints "Best School" 10 times, using "while" and include "Hi" at the 9th call.

i=1

while ((i <= 20)); do
    case $i in
	    4)
			printf "4\nbad luck from China\n"
			;;
		9)
			printf "9\ngood luck from Japan\n"
			;;
		17)
			printf "17\nbad luck from Italy\n"
			;;
		*)
        printf "%d\n" "$i"
		;;
    esac
    ((i++))
done
